name: CI

on:
  push:
    branches:
      - master

jobs:
  linux-sdist:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04@sha256:5747316366b8cc9e3021cd7286f42b2d6d81e3d743e2ab571f55bcd5df788cc8
    steps:
    - name: Install Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt-get update -q && \
        apt-get install -qy \
        git \
        gettext \
        python3 \
        python3-pip \
        python3-setuptools \
        faketime
    - uses: actions/checkout@v2
    - name: Build Linux source tarball
      run: cd contrib/build-linux/sdist && ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: Electrum-4.0.2-linux
        path: ./dist/Electrum-4.0.2.tar.gz
  windows:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04@sha256:b58746c8a89938b8c9f5b77de3b8cf1fe78210c696ab03a1442e235eea65d84f
    steps:
    - name: Install Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        dpkg --add-architecture i386 && \
        apt-get update -q && \
        apt-get install -qy \
            wget=1.19.4-1ubuntu2.2 \
            gnupg2=2.2.4-1ubuntu1.2 \
            dirmngr=2.2.4-1ubuntu1.2 \
            python3-software-properties=0.96.24.32.1 \
            software-properties-common=0.96.24.32.1 && \
        apt-get update -q && \
            apt-get install -qy \
            git=1:2.17.1-1ubuntu0.7 \
            p7zip-full=16.02+dfsg-6 \
            make=4.1-9.1ubuntu1 \
            mingw-w64=5.0.3-1 \
            autotools-dev=20180224.1 \
            autoconf=2.69-11 \
            libtool=2.4.6-2 \
            gettext=0.19.8.1-6
    - name: Install Wine
      run: |
        wget -nc https://dl.winehq.org/wine-builds/Release.key && \
            echo "c51bcb8cc4a12abfbd7c7660eaf90f49674d15e222c262f27e6c96429111b822 Release.key" | sha256sum -c - && \
            apt-key add Release.key && \
            rm Release.key && \
        wget -nc https://dl.winehq.org/wine-builds/winehq.key && \
            echo "78b185fabdb323971d13bd329fefc8038e08559aa51c4996de18db0639a51df6 winehq.key" | sha256sum -c - && \
            apt-key add winehq.key && \
            rm winehq.key && \
        apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/ && \
        apt-get update -q && \
        apt-get install -qy \
            wine-stable-amd64:amd64=4.0.3~bionic \
            wine-stable-i386:i386=4.0.3~bionic \
            wine-stable:amd64=4.0.3~bionic \
            winehq-stable:amd64=4.0.3~bionic
    - uses: actions/checkout@v2
    - name: Build Windows Package
      run: cd contrib/build-wine && ./build.sh