name: CI

on:
  push:
    branches:
      - master

jobs:
  linux-sdist:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04@sha256:5747316366b8cc9e3021cd7286f42b2d6d81e3d743e2ab571f55bcd5df788cc8
    steps:
    - name: Install Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt-get update -q && \
        apt-get install -qy \
        git \
        gettext \
        python3 \
        python3-pip \
        python3-setuptools \
        faketime
    - uses: actions/checkout@v2
    - name: Build Linux source tarball
      run: cd contrib/build-linux/sdist && ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: Electrum-4.0.2-linux
        path: ./contrib/build-linux/sdist/../../../dist/Electrum-4.0.2.tar.gz